export const courses = [
  // COMBO COURSES
  {
    id: 1,
    name: "Master in Cosmetology",
    type: "offline",
    category: "combo",
    desc: "Complete beauty training: makeup, hair, skin & nails.",
    summary: [
      "Makeup, Hair & Skin Care Training",
      "Advanced Beauty, Nail Extensions & Chemical Services",
      "Professional Certification · Practical Training · Career Support",
    ],
  },
  {
    id: 2,
    name: "Diploma in Cosmetology",
    type: "offline",
    category: "combo",
    desc: "Professional beauty training: makeup, hair, skin & basic nail techniques.",
    summary: [
      "Makeup, Hair Styling & Skin Care Basics",
      "Facials, Hair Treatments & Basic Chemical Services",
      "Certification · Practical Training · Career Guidance",
    ],
  },
  {
    id: 3,
    name: "Certificate in Cosmetology",
    type: "offline",
    category: "combo",
    desc: "Foundation beauty training: basic makeup, hair care & skin treatments.",
    summary: [
      "Basic Makeup, Hair Styling & Skin Care",
      "Facials, Threading, Waxing & Hair Treatments",
      "Certification · Practical Training · Beginner Friendly",
    ],
  },
  {
    id: 4,
    name: "Certificate in Self Grooming",
    type: "offline",
    category: "makeup",
    desc: "Personal grooming training: learn makeup, skincare & styling for everyday confidence.",
    summary: [
      "Daily Makeup & Personal Grooming Techniques",
      "Skincare Basics, Hair Styling & Dressing Tips",
      "Practical Training · Beginner Friendly · Certification",
    ],
  },
  {
    id: 5,
    name: "Certificate in International Makeup Artistry",
    type: "offline",
    category: "makeup",
    desc: "Advanced makeup training inspired by international beauty trends and techniques.",
    summary: [
      "HD, Airbrush & International Makeup Techniques",
      "Bridal, Fashion & Editorial Makeup Styles",
      "Professional Certification · Portfolio Development · Practical Training",
    ],
  },
  {
    id: 6,
    name: "Certificate in Professional Makeup Artistry",
    type: "offline",
    category: "makeup",
    desc: "Professional makeup course covering bridal, party & advanced makeup techniques.",
    summary: [
      "Bridal, Party & Engagement Makeup",
      "HD Makeup, Contouring & Skin Preparation",
      "Certification · Live Practice · Career Guidance",
    ],
  },
  {
    id: 7,
    name: "Certificate in Makeup Artistry",
    type: "offline",
    category: "makeup",
    desc: "Beginner to intermediate makeup training for aspiring makeup artists.",
    summary: [
      "Basic to Advanced Makeup Techniques",
      "Party Makeup, Day Makeup & Product Knowledge",
      "Certification · Hands-on Practice · Beginner Friendly",
    ],
  },
  {
    id: 8,
    name: "Certificate in International Nail Artistry",
    type: "offline",
    category: "nails",
    desc: "Advanced nail training with international nail art techniques and trends.",
    summary: [
      "Gel Extensions, Acrylic Nails & Advanced Nail Designs",
      "International Nail Art Techniques & Nail Care",
      "Professional Certification · Practical Training · Portfolio Development",
    ],
  },
  {
    id: 9,
    name: "Certificate in Professional Nail Artistry",
    type: "offline",
    category: "nails",
    desc: "Professional nail course covering nail extensions, nail art and salon techniques.",
    summary: [
      "Nail Extensions, Gel Polish & Nail Art Designs",
      "Nail Preparation, Shaping & Nail Care Techniques",
      "Certification · Hands-on Practice · Career Guidance",
    ],
  },
  {
    id: 10,
    name: "Certificate in Nail Artistry",
    type: "offline",
    category: "nails",
    desc: "Beginner nail training to learn basic nail art techniques and nail care.",
    summary: [
      "Basic Nail Art Designs & Gel Polish",
      "Nail Shaping, Nail Care & Product Knowledge",
      "Certification · Practical Training · Beginner Friendly",
    ],
  },
  {
    id: 11,
    name: "Certificate in Permanent Hair Extension",
    type: "offline",
    category: "hair",
    desc: "Professional training in permanent hair extension techniques and application.",
    summary: [
      "Permanent Hair Extension Techniques",
      "Extension Application, Blending & Maintenance",
      "Certification · Hands-on Practice · Professional Skills",
    ],
  },
  {
    id: 12,
    name: "Certificate in Barbering",
    type: "offline",
    category: "hair",
    desc: "Professional barber training covering modern haircuts, beard styling and grooming.",
    summary: [
      "Men’s Hair Cutting & Fade Techniques",
      "Beard Styling, Grooming & Shaving Techniques",
      "Certification · Practical Training · Salon Skills",
    ],
  },
  {
    id: 13,
    name: "Certificate in International Hair Styling",
    type: "offline",
    category: "hair",
    desc: "Advanced hair styling training inspired by international salon trends.",
    summary: [
      "Advanced Hair Styling & Creative Looks",
      "Bridal, Party & Fashion Hair Styles",
      "Certification · Portfolio Development · Practical Training",
    ],
  },
  {
    id: 14,
    name: "Certificate in Hair Styling",
    type: "offline",
    category: "hair",
    desc: "Professional hair styling course covering basic to advanced styling techniques.",
    summary: [
      "Hair Styling Tools & Techniques",
      "Party, Bridal & Occasion Hairstyles",
      "Certification · Hands-on Practice · Career Guidance",
    ],
  },
  {
    id: 15,
    name: "Certificate in Professional Hair Craftsmanship",
    type: "offline",
    category: "hair",
    desc: "Comprehensive training in professional hair cutting, styling and treatments.",
    summary: [
      "Hair Cutting, Styling & Professional Techniques",
      "Hair Treatments, Blow Dry & Styling Skills",
      "Certification · Practical Training · Salon Ready Skills",
    ],
  },
  {
    id: 16,
    name: "Certificate in Hair Craftsmanship",
    type: "offline",
    category: "hair",
    desc: "Foundation course to learn essential hair cutting and styling techniques.",
    summary: [
      "Basic Hair Cutting & Styling Techniques",
      "Hair Care, Blow Dry & Tool Handling",
      "Certification · Practical Training · Beginner Friendly",
    ],
  },
  {
    id: 17,
    name: "Certificate in Eye Lashes Extension",
    type: "offline",
    category: "beauty",
    desc: "Professional training in eyelash extension techniques and lash styling.",
    summary: [
      "Classic & Volume Eyelash Extension Techniques",
      "Lash Application, Styling & Maintenance",
      "Certification · Practical Training · Professional Skills",
    ],
  },
  {
    id: 18,
    name: "Certificate in Aesthetician",
    type: "offline",
    category: "beauty",
    desc: "Professional skincare training covering facial treatments and advanced skin care.",
    summary: [
      "Skin Analysis & Professional Facial Techniques",
      "Advanced Skincare Treatments & Skin Care Products",
      "Certification · Practical Training · Career Guidance",
    ],
  },
  {
    id: 19,
    name: "Certificate in Beauty Therapist",
    type: "offline",
    category: "beauty",
    desc: "Comprehensive beauty therapy training for salon services and skincare treatments.",
    summary: [
      "Facials, Waxing, Threading & Basic Beauty Services",
      "Skin Care Treatments & Client Consultation",
      "Certification · Hands-on Practice · Salon Skills",
    ],
  },
  {
    id: 20,
    name: "Certificate in Skincare",
    type: "offline",
    category: "beauty",
    desc: "Foundation course to learn essential skincare techniques and facial treatments.",
    summary: [
      "Basic Skincare, Facials & Skin Analysis",
      "Product Knowledge & Skin Care Routine",
      "Certification · Practical Training · Beginner Friendly",
    ],
  },
];
